services:
    nachtelb.imprint.controller:
        class: nachtelb\imprint\controller\main
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
    nachtelb.imprint.listener:
        class: nachtelb\imprint\event\main_listener
        arguments:
            - @controller.helper
            - @template
        tags:
            - { name: event.listener }
